### ISSUE TITLE
[1.18.2] Crash with Patrols of Factioncraft

### ISSUE THREAD

**Issue by Aarods** [CCr4ft3r/DimensionalThreading-Reforged#11]
Minecraft Version
1.18.2

Mod Version
1.2.8

Notes
According to what I saw, when spawning a "Faction craft" faction in the world, the server automatically shuts down and throws a crash report.

Crash Report
[crash-2023-08-01_21.17.19-server.txt](https://github.com/CCr4ft3r/DimensionalThreading-Reforged/files/12234140/crash-2023-08-01_21.17.19-server.txt)

Image 
![image](https://github.com/CCr4ft3r/DimensionalThreading-Reforged/assets/110215990/b3d5b011-2b06-4006-91db-e324e3048700)

**Comment by CCr4ft3r** [comment]
Just like many other issues this needs to be resolved on the other side. If you take a look into the stacktrace of the exception you will notice that the exception is actual being caused by Patrols of Fractioncraft. 
It was probably not implemented considering being inside a multithreaded environment.
