### ISSUE TITLE
[1.19.2] Excessive Mob Spawns

### ISSUE THREAD

**Issue by Reshy** [CCr4ft3r/DimensionalThreading-Reforged#15]
Logs:  https://pastebin.com/Ur4C2XxW

![image](https://github.com/CCr4ft3r/DimensionalThreading-Reforged/assets/2096384/816d494d-3186-4a73-aa83-ab7a01fcf3f5)

Something's malfunctioning with Dimensional Threading that causes thousands of mobs to spawn.  Not sure precisely what causes it, but it's very disruptive.

**Comment by CCr4ft3r** [comment]
Seems like an issue of TansHugeTrees. Try to remove it.

**Comment by Maypul** [comment]
I confirm I have the same issue when I add this mod to my modpack. I do not use TansHugeTrees or Pehkui. Here's my modlist currently used on a server. It all seems to work great once DT Reforged is removed. Server spawns like 65k mobs, gets average tick to 650 ms, when player is on server ,they get 1 fps and when they look at the ocean it is all filled with mobs. /kill @e does not help because mobs repopulate in few seconds. Interesting thing is I did not find this bug for a long time when testing it on my server, it happened because either I kill all mobs, it seems then there is no more limits for mobs anymore, or in creative mode I done my usual lag test, to place a torch, remove it and repeat in short time, it seemed to cause the mobs to start spawning. Once mod is removed, mobs do spawn correctly. My server's mod list: https://pastebin.com/F1xeqhPX

**Comment by CCr4ft3r** [comment]
For this I would need the latest.log

**Comment by Maypul** [comment]
Here's the log. I readded Dimensional-Threading-Reforged-1.19.2-1.2.8 and removed new addition: SpawncapControlUtility-1.19-41.1.2.0 (with this mod I could not cause spawn to break).
Currently there are no mobs spawned:
![image](https://github.com/CCr4ft3r/DimensionalThreading-Reforged/assets/98578889/46575ea8-236c-4518-b4c5-034af09d0b68)
Here's after I started spam in creative mode placement of torches and their removal with destroying blocks:
![image](https://github.com/CCr4ft3r/DimensionalThreading-Reforged/assets/98578889/62c4baa6-bb70-43d6-8d17-46fd21cb56fe)
Then I flew around and found this:
![image](https://github.com/CCr4ft3r/DimensionalThreading-Reforged/assets/98578889/d09798c6-087c-48f3-9e25-b794c94df24e)
Even though this time, killing all entities did not give such big numbers yet, but their numbers started to grow.

Latest log of server: https://pastebin.com/KVHbC33a

Excuse me, I forgot to remove LogBegone, so this log is filtered of some non-issue messages, like standard warning or mod errors when it could not load recipe because addon mod was not there.

**Comment by F0xtastic** [comment]
Had a client with the same issue. Spams this error while mobs are spawning: "A mod is trying to add an entity from offthread, this should be avoided."

Removing Dimensional Threading immediately resolved it.

Here it is before it was removed, just in case it's helpful: https://mclo.gs/GGwnVUU

**Comment by CCr4ft3r** [comment]
Cupboard doesn't support a multithread environment. And they are not willing to fix it. 
The only solution is to remove Cupboard or DimThread.

**Comment by vgrynch** [comment]
I think its a nature of how Cupboard works. In the configs, you can find this:
```
"logOffthreadEntityAdd": {
    "desc:": "Entities should only be added on the server thread itself, cupboard fixes the crashes caused by mods violating that, this option enables the logging of those: default:true",
    "logOffthreadEntityAdd": true
  }
}
```
For some reason, or they know something because they say "Entities should only be added on the server thread itself".
I tend to believe them, Minecraft was not developed as multi-threaded, and many platforms that extend Minecraft tend to follow that rule.

**Comment by CCr4ft3r** [comment]
multithreaded ticking for entities could cause issues (without deeper changes) but adding them like DimThread does not cause issues by itself.
