### ISSUE TITLE
[1.19.2] Weird crash.

### ISSUE THREAD

**Issue by togera13** [CCr4ft3r/DimensionalThreading-Reforged#16]
[crash-2023-11-04_04.49.40-server.txt](https://github.com/CCr4ft3r/DimensionalThreading-Reforged/files/13275443/crash-2023-11-04_04.49.40-server.txt)
[2023-11-04-4.log](https://github.com/CCr4ft3r/DimensionalThreading-Reforged/files/13275444/2023-11-04-4.log)
https://github.com/zlainsama/CosmeticArmorReworked/issues/100

Tbh I do have create & didn't realize this mod had incompatibility with it so maybe this was caused by that upon re-reading the modpage; but if it isn't it was a very weird crash in the nether upon killing a magma slime & I had to remove my cosmetic armor save file temporarily to fix it.

**Comment by SrRapero720** [comment]
Your issue was a level.dat corrupted and doesn't look like was caused by DimThreads
try opening it with [NBTExplorer](https://github.com/jaquadro/NBTExplorer/releases/tag/v2.8.0-win) to see what key/value was corrupted.

even if was the case you can delete it and minecraft can regenerate it. is what i do when i remove a mod witch adds custom biomes
