### ISSUE TITLE
server crash on arclight 1.19.2

### ISSUE THREAD

**Issue by sj-hub9796** [CCr4ft3r/DimensionalThreading-Reforged#2]
Crash reproduction: start server with only this mod. and wait a seconds

crash report:
[crash-2023-04-10_23.58.55-server.txt](https://github.com/CCr4ft3r/DimensionalThreading-Reforged/files/11191346/crash-2023-04-10_23.58.55-server.txt)

**Comment by CCr4ft3r** [comment]
Seems like that Arclight doesn't support multithreaded environment or that their code isn't thread-safe.
https://github.com/IzzelAliz/Arclight/blob/07a3fd1b5dace2bc4cb33fdf471c2af5af585bc1/arclight-forge/src/main/java/io/izzel/arclight/boot/asm/AsyncCatcher.java#L247

Sorry, but this can probably only be fixed by Arclight itself. Maybe it's worth it to report this issue to their repo: https://github.com/IzzelAliz/Arclight/issues
